services:
  # ===================== ELASTICSEARCH =====================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
      interval: 20s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
  # ===================== KAFKA ======================
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: "false"
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8078:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: true
    restart: on-failure

  # ===================== POSTGRES =====================
  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    restart: always

  postgres-user:
    image: postgres:16
    container_name: postgres-user
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpass
    restart: always

  postgres-vacancy:
    image: postgres:16
    container_name: postgres-vacancy
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: vacancydb
      POSTGRES_USER: vacancyuser
      POSTGRES_PASSWORD: vacancypass
    restart: always

  postgres-resume:
    image: postgres:16
    container_name: postgres-resume
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: resumedb
      POSTGRES_USER: resumeuser
      POSTGRES_PASSWORD: resumepass
    restart: always

  postgres-application:
    image: postgres:16
    container_name: postgres-application
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: applicationdb
      POSTGRES_USER: applicationuser
      POSTGRES_PASSWORD: applicationpass
    restart: always

  postgres-skill:
    image: postgres:16
    container_name: postgres-skill
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: skilldb
      POSTGRES_USER: skilluser
      POSTGRES_PASSWORD: skillpass
    restart: always

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
       - "3001:3000"
    environment:
       - GDS_INSTALL_PLUGINS=grafana-loki-datasource
    depends_on:
       - loki
