apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: laborexchange
type: Opaque
stringData:
  user-username: useruser
  user-password: userpass
  vacancy-username: vacancyuser
  vacancy-password: vacancypass
  resume-username: resumeuser
  resume-password: resumepass
  application-username: applicationuser
  application-password: applicationpass
  skill-username: skilluser
  skill-password: skillpass
  statistics-username: statsuser
  statistics-password: statspass
  chat-username: chatuser
  chat-password: chatpass
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: laborexchange
type: Opaque
stringData:
  jwt-secret: supersecretkeyforjwtinjobexchange
  mail-password: ambd yxwy vhon utxp
